### ISSUE TITLE
授权登陆返回错误

### ISSUE THREAD

**Issue by lucawoo** [TencentCloudBase/tcb-js-sdk#1]
（一）前置条件：
1、已经设置授权回调域名
2、已经设置web域名白名单

（二）请求（参数已经改为自己的）：
tcb.init({
  env: 'xxxx-yyy'
});

tcb.auth({
  persistence: 'session'
}).weixinAuthProvider({
  appid: 'wx73932328juof23',
  scope: 'snsapi_base'
}).signIn(function(err, res) {

})

（三）返回：
{"code":"INVALID_REQUEST_SOURCE","message":"Invalid request source"}

**Comment by lucawoo** [comment]
ERROR in ./~/tcb-js-sdk/dist/index.js
Module not found: Error: Can't resolve '@cloudbase/database' in

**Comment by chhpt** [comment]
第一个问题：请检查配置的安全域名是否误带了 https 或 http 协议，正确的配置是不带有 http 协议的，比如：`tencent.com`

第二个问题，请升级到最新的版本：`1.1.2`
