### ISSUE TITLE
如何在react-native中调用

### ISSUE THREAD

**Issue by puti94** [TencentCloudBase/tcb-js-sdk#11]
已经传入自定义adapter，也创建并且添加了appSign，还是提示还需要appSecret，这个参数是如何生成的？
`
import tcb, {TCB} from 'tcb-js-sdk';
import {adapter} from './rnAdapter';
 app = tcb.init({
      env: 'xxxx',
      appSign: 'xxxx',
      appSecret: {
        appAccessKey: 'xxxx',
        appAccessKeyId: 'xxxx',
      },
      adapter,
    });
    app.useAdapters({
      genAdapter: () => adapter,
      runtime: 'react-native',
      isMatch: () => true,
    });
`
调用匿名登录api测试下，会返回 [SYS_ERR]非法的应用凭证，请前往控制台用户管理页获取

**Comment by hyrijk** [comment]
试了下把 sdk Web.ts 复制出来，简单修改下可以运行。`runtime` 继续填 `web`，不需要 `appSecret`
```javascript
function genAdapter() {
  const reqClass: any = WebRequest
  const wsClass: any = WebSocket
  const adapter: SDKAdapterInterface = {
    reqClass,
    wsClass,
    root: global
    // localStorage: localStorage,
    // sessionStorage: sessionStorage
  }
  return adapter
}

const isMatch = () => true
const runtime = 'web'

export { genAdapter, isMatch, runtime }

```

**Comment by puti94** [comment]
是可以跑，但是验证通不过，功能都用不了

**Comment by hyrijk** [comment]
好像是有跨域的限制，抓包看了下 `origin` 是 `file://`。
`WebRequest` 里面加了这个可以匿名登录成功。
```
ajax.setRequestHeader('origin', 'localhost:8080')
```
我只试了匿名登录，然后调用云函数成功了，其他功能没试。
```javascript
// init 之前先 use
tcb.useAdapters([RNAdapter])
const app = tcb.init({
  env: 'xxxx'
})

```

**Comment by puti94** [comment]
这样是可以解决匿名登录的问题了，但是我之前测试过自定义登录，接口报了个environment not match 的错误，兄弟有没有碰过，在react测试的

**Comment by hyrijk** [comment]
没有，自定义登录正准备开始写来着

**Comment by hyrijk** [comment]
自定义登录正常  
`auth.customAuthProvider().signIn(ticket)`和`auth.linkAndRetrieveDataWithTicket(ticket)`都是好的
https://gist.github.com/hyrijk/23dbb6d95b21f26341581b10c1181e0e

**Comment by puti94** [comment]
`
const tcb = require('tcb-admin-node')
const credentials = require('./pem.json');
const app = tcb.init({
  env: tcb.getCurrentEnv(),
  credentials
});
exports.main = async function (event) {
`
晕了，之前环境问题是因为我初始化放在云函数外面了，tcb.getCurrentEnv() 这个方法获取环境获取不到
