### ISSUE TITLE
nuxt上报window is not defined

### ISSUE THREAD

**Issue by Milker90** [TencentCloudBase/tcb-js-sdk#14]
nodejs:v10.16.0
npx:v6.9.0
使用SSR模式

部分代码：
```
<script>
import tcb from "tcb-js-sdk";
export default {
  async asyncData({ req, res }) {
    const app = tcb.init({
      env: "xxx"
    });

    const auth = app.auth();
    const loginState = auth.hasLoginState();
    if (loginState == null) {
      loginState = await auth.anonymousAuthProvider().signIn();
    }

    const res = await app.callFunction({
      name: "xxx"
    });
    const result = res.result;
    console.log(result);

    return { detail: result };
  }
}
</script>
```

报错:
 ERROR  window is not defined      
                                                                                                                                                               
  at Object.genAdapter (node_modules/tcb-js-sdk/dist/adapters/platforms/web.js:186:15)
  at Object.useDefaultAdapter (node_modules/tcb-js-sdk/dist/adapters/index.js:33:22)
  at TCB._useDefaultAdapter (node_modules/tcb-js-sdk/dist/index.js:207:29)
  at TCB.init (node_modules/tcb-js-sdk/dist/index.js:90:18)
  at asyncData (6b7c181dac68c2fc6578.js:1:1308)
  at k (server.js:1:887933)
  at Promise.all._.map.n (server.js:1:905680)
  at Array.map (<anonymous>)
  at t.default (server.js:1:905589)

(node:52436) UnhandledPromiseRejectionWarning: ReferenceError: window is not defined
    at Object.genAdapter (/Users/tommy/Desktop/zq-sls/zq-web/node_modules/tcb-js-sdk/dist/adapters/platforms/web.js:186:15)
    at Object.useDefaultAdapter (/Users/tommy/Desktop/zq-sls/zq-web/node_modules/tcb-js-sdk/dist/adapters/index.js:33:22)
    at TCB._useDefaultAdapter (/Users/tommy/Desktop/zq-sls/zq-web/node_modules/tcb-js-sdk/dist/index.js:207:29)
    at TCB.init (/Users/tommy/Desktop/zq-sls/zq-web/node_modules/tcb-js-sdk/dist/index.js:90:18)
    at asyncData (6b7c181dac68c2fc6578.js:1:1308)
    at k (server.js:1:887933)
    at Promise.all._.map.n (server.js:1:905680)
    at Array.map (<anonymous>)
    at t.default (server.js:1:905589)

**Comment by anti996sz** [comment]
我用的也是nuxt.js + tcb的方式在开发一个WEB应用，目前基本上能用，tcb.init()只能在浏览器中运行，所以我放在了插件中注入到Vue实例：

`import Vue from "vue";
import tcb from "tcb-js-sdk";

const cloudbase = tcb.init({
  env: "xxxx"
});

Vue.prototype.$cloudbase = cloudbase;`

页面可以在async created()调用，或者以页面的一个事件方法调用：

`    test() {
      let loginState = this.$cloudbase.auth().hasLoginState();
      console.log(loginState);

      if (!loginState) return;

      this.$cloudbase
        .database()
        .collection("xxx")
        .get()
        .then(console.log);`

**Comment by Milker90** [comment]
> 我用的也是nuxt.js + tcb的方式在开发一个WEB应用，目前基本上能用，tcb.init()只能在浏览器中运行，所以我放在了插件中注入到Vue实例：
> 
> `import Vue from "vue";
> import tcb from "tcb-js-sdk";
> 
> const cloudbase = tcb.init({
> env: "xxxx"
> });
> 
> Vue.prototype.$cloudbase = cloudbase;`
> 
> 页面可以在async created()调用，或者以页面的一个事件方法调用：
> 
> ` test() {
> let loginState = this.$cloudbase.auth().hasLoginState();
> console.log(loginState);
> 
> ```
>   if (!loginState) return;
> 
>   this.$cloudbase
>     .database()
>     .collection("xxx")
>     .get()
>     .then(console.log);`
> ```

@anti996sz 你有可行的demo吗？我也试了你这种方法，但是在created中打印的this.$cloudbase为null，我对nutx也不是很了解，ssr现在卡在了这里。

**Comment by anti996sz** [comment]
https://github.com/anti996sz/nuxt-tcb
Add .env file at the root folder, and set tcb env id in .env file as: 
tcb_env=xxxx

**Comment by anti996sz** [comment]
注意created()方法前加上async，使用 
```async created(){
    ...
}```

**Comment by Milker90** [comment]
参考腾讯云官网文章：https://mp.weixin.qq.com/s/zJ1cm9oCbWtIZ0bpf5LkTw

**Comment by g8up** [comment]
我是用官方的 express 模板创建的云函数，也遇到了相似报错：window is not defined
```json
{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"ReferenceError: window is not defined\n    at Object.genAdapter (/var/user/node_modules/@cloudbase/utilities/dist/adapters/platforms/web.js:201:15)\n    at useDefaultAdapter (/var/user/node_modules/@cloudbase/utilities/dist/adapters/index.js:46:22)\n    at Cloudbase._useDefaultAdapter (/var/user/node_modules/@cloudbase/app/dist/cjs/index.js:213:18)\n    at Cloudbase.init (/var/user/node_modules/@cloudbase/app/dist/cjs/index.js:129:18)\n    at Object.\u003canonymous\u003e (/var/user/models/bread-order.js:3:23)\n    at Module._compile (internal/modules/cjs/loader.js:701:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)\n    at Module.load (internal/modules/cjs/loader.js:600:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:531:3)","statusCode":430}
```
