### ISSUE TITLE
local类型的auth，在页面刷新后tcb登录状态无法通过getLoginState找回

### ISSUE THREAD

**Issue by anti996sz** [TencentCloudBase/tcb-js-sdk#17]
问题：
页面刷新前tcb已经匿名登录，页面刷新后，在浏览器的localStorage中还保存着tcb的登录状态数据，但却无法通过auth().getLoginState()得到刷新前的登录状态。通过Ticket登录没有此问题。

官方文档说：
local：在显式退出登录之前的 30 天内保留身份验证状态

现页面刷新一下就没了，是不是BUG？
可以提供一个setLoginState(loginState)的方法来解决这个问题吗？

**Comment by zhoujunpeng** [comment]
@anti996sz 是不是直接调用的`tcb.auth()`？如下
```javascript
import tcb from 'tcb-js-sdk';
const app = tcb.init({
  // ...
});
const auth = tcb.auth();
// 获取登录态
console.log(auth.getLoginState());
```

虽然这样不会报错，但是建议**调用`app.auth()`而不是`tcb.auth()`**。

tcb可以创建多个app分别对应不同的环境id，每个app都是一个封闭的命名空间，互相之间的状态不共享。所以上述代码在调用`tcb.auth()`后实际上与前面的app属于不同的命名空间。所以上述代码更正后如下：
```javascript
import tcb from 'tcb-js-sdk';
const app = tcb.init({
  // ...
});
const auth = app.auth();
// 获取登录态
console.log(auth.getLoginState());
```

**Comment by anti996sz** [comment]
问题没有确定就关掉了？问题并是像楼上所述，实际情况是使用 tcb + vue.js 来开发，tcb实例全局实例化一次，后面各个页面只是使用tcb实例化后的全局的变量而已，各个页面也不会创建新的tcb实例，所以不存在刷新页面创建新的实例，不是楼上所说的情形。
