### ISSUE TITLE
判断登陆状态是否过期的方法

### ISSUE THREAD

**Issue by chenmingwei** [TencentCloudBase/tcb-js-sdk#2]
在网页开发中
有没有判断登陆是否已经登陆的方法,文档中没找到
登陆成功后url上都会带一个code，手动清除掉code后又会再次调用登陆方法
如有登陆判断的方法就可以在调用登陆方法前判断

**Comment by chhpt** [comment]
这个暂时不支持，会在下一个版本中加上
