### ISSUE TITLE
callFunction 方法的入参，文档里写的和 .d.ts 文件里写的不一致 

### ISSUE THREAD

**Issue by litao36253** [TencentCloudBase/tcb-js-sdk#20]
文档里
![image](https://user-images.githubusercontent.com/22752122/83348326-10a93780-a35e-11ea-8b9e-9c77f31cf6a3.png)
字段 | 类型 | 必填 | 说明
name | string | 是 | 云函数名称
data | object | 否 | 云函数参数
callback | function | 否 | 回调函数

.d.ts 文件里
![image](https://user-images.githubusercontent.com/22752122/83348340-2dde0600-a35e-11ea-9392-aedd02d44bae.png)
callFunction(params: {
        name: string;
        data: any;
        query: any;
        parse: boolean;
    }, callback?: Function): any

这使得我在用ts开发时，data、query、parse都是必传参

**Comment by roshad** [comment]
五月的issue到8月了没人看一眼么,腾讯不打算继续搞了?

**Comment by zhoujunpeng** [comment]
已修正
