### ISSUE TITLE
在微信小游戏中可以直接使用tcb的接口weixinAuthProvider进行微信授权登陆吗？

### ISSUE THREAD

**Issue by 0odrifto0** [TencentCloudBase/tcb-js-sdk#21]
在使用cocos开发小游戏，使用了tcb，测试发现匿名登陆的情况下，微信小游戏上可以正常登陆。在使用微信授权登陆时会报如下的错误：[INVALID_PARAM] [100004] this record is not exist

**Comment by zhoujunpeng** [comment]
@0odrifto0 不能
