### ISSUE TITLE
希望提供Dart版sdk

### ISSUE THREAD

**Issue by DaZiYuan** [TencentCloudBase/tcb-js-sdk#3]
Dart目前正热，我个人认为可以搞一搞...

**Comment by chhpt** [comment]
@DaZiYuan 在规划中，欢迎关注~

**Comment by DaZiYuan** [comment]
希望尽快出dart版sdk。Dart可以封装js接口，我手工在AngularDart项目中尝试，无奈工作量太大弃了。希望官方早日支持。。

flutter for web昨夜已经发布beta版了。

**Comment by chhpt** [comment]
@DaZiYuan Flutter SDK 已经有了哈 http://docs.cloudbase.net/api-reference/flutter/install.html
