### ISSUE TITLE
Vue Typescript 工程引用报错

### ISSUE THREAD

**Issue by DaZiYuan** [TencentCloudBase/tcb-js-sdk#4]
重现步骤
```
//创建vue工程，勾选ts
vue create test-project 
npm install --save tcb-js-sdk@latest
import TCB from 'tcb-js-sdk'
yarn serve
```
import tcb就会报错
![image](https://user-images.githubusercontent.com/80653/69703118-b10e6d00-112b-11ea-8e12-b0fae33aa351.png)

**Comment by DaZiYuan** [comment]
```
/**
 * @internal
 */
class Request {
```
为什么要声明为internal

**Comment by DaZiYuan** [comment]
ts 支持不好，很多类型都找不到。外面调用类型全部得用any
希望早日支持ts...

**Comment by chhpt** [comment]
@DaZiYuan 你好，在 Vue CLI 创建的普通工程以及 TS 工程中均未复现你提及的问题，请提供能够复现问题的最小 demo，建议使用 Git 仓库或者 [codesandbox](https://codesandbox.io)提供 demo。

**Comment by DaZiYuan** [comment]
我又试了一下确实没能重现，可能是我之前的电脑环境有问题。打扰了
