### ISSUE TITLE
网页刷新后如何维持登录态

### ISSUE THREAD

**Issue by franksonet** [TencentCloudBase/tcb-js-sdk#7]
web端tcb使用后端传递的ticket登录之后如果在网页刷新之后还能维持登录态？
尝试用localStorage保存，但没有效果

**Comment by anti996sz** [comment]
tcb本身如果使用的是tcb.auth({‘local'})的话，在调用数据库操作前执行tcb.auth().hasLoginState()会自动将登录信息从本地加载，不需要额外处理。

**Comment by zhoujunpeng** [comment]
@franksonet 按照 @anti996sz 的回复在创建auth时制定persistence为local即可：
```javascript
const app = tcb.init({
  // ...
})
const auth = app.auth({
  persistence: 'local'
})
```

文档参照https://docs.cloudbase.net/api-reference/web/authentication.html#app-auth

**Comment by franksonet** [comment]
了解，多谢！
